env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - react
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier: [1, { singleQuote: true, jsxSingleQuote: true }]
  react/jsx-uses-react: 2
  react/react-in-jsx-scope: 0
  import/no-unresolved: 0
  import/no-cycle: 2
  import/no-anonymous-default-export: 2
  '@typescript-eslint/explicit-module-boundary-types': 2
